FROM python:3.9
WORKDIR /app

COPY api/requirements.txt api/run.py api/.env ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production
ENV DEBUG False

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]